version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: spacefleet-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - spacefleet-network

volumes:
  db_data:

networks:
  spacefleet-network:
    driver: bridge
